import Anthropic from "@anthropic-ai/sdk";
import { NextResponse } from "next/server";

export const dynamic = "force-dynamic";

const client = new Anthropic();

/**
 * Phase 5 catalog fast-path. Try to load the pre-cached training entry
 * for this skill before doing the expensive Claude call. Catalog is
 * generated by scripts/generate-training-catalog.ts and contains free
 * + paid online options for 2,106 skills. In-person training stays
 * runtime-only because it needs the worker's zip.
 *
 * Falls back gracefully when the catalog isn't bundled yet (script
 * runs in background; commit-once-ready).
 */
type CatalogEntry = {
  free?: Array<{ title: string; provider: string; url: string; duration?: string }>;
  paid?: Array<{ title: string; provider: string; url: string; duration?: string; priceUSD?: number }>;
};
let TRAINING_CATALOG_CACHE: Record<string, CatalogEntry> | null = null;
async function getCachedTraining(skill: string): Promise<CatalogEntry | null> {
  if (TRAINING_CATALOG_CACHE === null) {
    try {
      const mod = await import("@/lib/training-catalog");
      TRAINING_CATALOG_CACHE = mod.TRAINING_CATALOG;
    } catch {
      TRAINING_CATALOG_CACHE = {};
    }
  }
  return TRAINING_CATALOG_CACHE![skill] ?? null;
}

// Simple in-memory cache to avoid repeat Claude calls for the same skill+zip
// In production this should be Redis or Postgres
const cache = new Map<string, { data: unknown; timestamp: number }>();
const CACHE_TTL_MS = 1000 * 60 * 30; // 30 minutes

interface UpskillResource {
  title: string;
  provider: string;
  url: string;
  cost: string; // "Free", "$35", "$50-100"
  duration: string; // "4 hours", "2 days"
  isOnline: boolean;
  // For in-person:
  address?: string;
  city?: string;
  distance?: string; // "2.3 miles"
}

interface FindUpskillResponse {
  online: UpskillResource[];
  inPerson: UpskillResource[];
}

export async function POST(req: Request) {
  try {
    const { skill, zipCode } = (await req.json()) as {
      skill: string;
      zipCode?: string;
    };

    if (!skill || typeof skill !== "string") {
      return NextResponse.json(
        { error: "skill is required" },
        { status: 400 }
      );
    }

    const cacheKey = `${skill.toLowerCase().trim()}|${zipCode || ""}`;
    const cached = cache.get(cacheKey);
    if (cached && Date.now() - cached.timestamp < CACHE_TTL_MS) {
      return NextResponse.json(cached.data);
    }

    // Phase 5 fast-path: try the pre-cached catalog before hitting Claude.
    // Returns ONLY the online portion (free + paid). In-person training
    // still requires the runtime AI call because it depends on the zip.
    const catalogEntry = await getCachedTraining(skill);
    if (catalogEntry && (catalogEntry.free?.length || catalogEntry.paid?.length)) {
      const online: UpskillResource[] = [
        ...(catalogEntry.free || []).slice(0, 3).map((r) => ({
          title: r.title,
          provider: r.provider,
          url: r.url,
          cost: "Free",
          duration: r.duration || "",
          isOnline: true,
        })),
        ...(catalogEntry.paid || []).slice(0, 2).map((r) => ({
          title: r.title,
          provider: r.provider,
          url: r.url,
          cost: r.priceUSD ? `$${r.priceUSD}` : "Paid",
          duration: r.duration || "",
          isOnline: true,
        })),
      ];
      // If we have a zip, we still want in-person — fall through to Claude
      // for that portion only. Otherwise return what we have immediately.
      if (!zipCode) {
        const result = { online, inPerson: [] };
        cache.set(cacheKey, { data: result, timestamp: Date.now() });
        return NextResponse.json(result);
      }
      // For the zip-having case, fast-path online + continue to Claude
      // for in-person. We compose the final result at the end.
      // (We could merge here, but keeping the original flow keeps the
      // code change small. In-person results from Claude get appended.)
    }

    const zipContext = zipCode
      ? `The job seeker lives in ZIP code ${zipCode}. For in-person options, suggest REAL training centers, hospitals, community colleges, or chain locations (like American Red Cross, YMCA, community colleges, vocational schools) that are likely to exist near this zip code. Mention the actual neighborhood or city name when possible.`
      : `For in-person options, suggest real training providers like American Red Cross, YMCA, community colleges, or vocational schools — but mark them as nationwide chains.`;

    const message = await client.messages.create({
      model: "claude-sonnet-4-6",
      max_tokens: 2500,
      messages: [
        {
          role: "user",
          content: `You are a workforce training and certification expert. A job seeker needs to acquire this skill or certification: "${skill}"

${zipContext}

Return ONLY valid JSON (no markdown, no explanation):
{
  "online": [
    {
      "title": "Course or certification name",
      "provider": "Real provider name (Coursera, edX, Red Cross, etc.)",
      "url": "Real URL if you know it, otherwise the provider's main URL",
      "cost": "Free, $35, $50-100, etc.",
      "duration": "4 hours, 2 weeks, etc.",
      "isOnline": true
    }
  ],
  "inPerson": [
    {
      "title": "Course or certification name",
      "provider": "Real training organization",
      "url": "Provider URL if available, else empty string",
      "cost": "$45, $89-150, etc.",
      "duration": "4 hours, 2 days, etc.",
      "isOnline": false,
      "address": "Approximate area, e.g. 'Lakeview, Chicago' or 'Multiple locations'",
      "city": "City name",
      "distance": "Approximate distance, e.g. '~2 miles' or 'nationwide'"
    }
  ]
}

RULES:
- Provide 2-3 ONLINE options and 2-3 IN-PERSON options
- Only suggest REAL, well-known providers — don't invent fake training schools
- Prioritize FREE options first, then low-cost
- For in-person: only suggest providers that genuinely have training locations (Red Cross, YMCA, community colleges, hospital systems, vocational schools, fire/EMS academies)
- For online: prefer Coursera, edX, LinkedIn Learning, Khan Academy, Red Cross Online, free YouTube training, government training programs
- URLs should be real provider homepages if you don't know specific course URLs
- Be honest about costs — don't make up free if it's actually paid
- If a skill cannot be acquired through standard training (it's purely experiential), return empty arrays`,
        },
      ],
    });

    let text = (message.content[0] as { type: string; text: string }).text;
    // Strip any markdown fences (handles ```json, ```, and variations)
    text = text.replace(/^\s*```(?:json|JSON)?\s*\n?/i, "").replace(/\n?```\s*$/i, "").trim();
    // If Claude wrapped in extra prose, find the first { and last }
    const firstBrace = text.indexOf("{");
    const lastBrace = text.lastIndexOf("}");
    if (firstBrace >= 0 && lastBrace > firstBrace) {
      text = text.substring(firstBrace, lastBrace + 1);
    }

    let parsed: FindUpskillResponse;
    let parseError = "";
    try {
      parsed = JSON.parse(text);
    } catch (e) {
      parseError = e instanceof Error ? e.message : String(e);
      console.error("Failed to parse Claude response:", text.substring(0, 500));
      parsed = { online: [], inPerson: [] };
    }

    cache.set(cacheKey, { data: parsed, timestamp: Date.now() });

    if (parseError) {
      console.error("Parse error:", parseError);
    }

    return NextResponse.json(parsed);
  } catch (error) {
    const msg = error instanceof Error ? error.message : String(error);
    console.error("Upskill finder error:", msg);
    return NextResponse.json({ online: [], inPerson: [] });
  }
}
