/**
 * BLS Occupational Data Pipeline
 *
 * Embedded Bureau of Labor Statistics data for the top 50 occupations
 * relevant to the PayRanker platform. Data sourced from the BLS
 * Occupational Outlook Handbook (https://www.bls.gov/ooh/).
 *
 * AI Exposure Scores follow Karpathy-style reasoning:
 *   0-3  = physical / hands-on work, low LLM displacement
 *   4-6  = mixed cognitive + physical, moderate exposure
 *   7-9  = primarily cognitive / knowledge work, high exposure
 *   9-10 = pure data processing / routine cognitive, highest exposure
 */

export interface BLSOccupation {
  title: string;
  blsCode: string;
  medianPay: number;
  payType: "hourly" | "annual";
  medianHourly: number;
  totalEmployment: number;
  growthOutlook: string;
  growthPercent: number;
  educationRequired: string;
  aiExposureScore: number;
  relatedSkills: string[];
  vertical: string;
}

export const BLS_OCCUPATIONS: BLSOccupation[] = [
  // ── Healthcare (10) ──────────────────────────────────────────────────
  {
    title: "Home Health and Personal Care Aides",
    blsCode: "31-1120",
    medianPay: 32240,
    payType: "annual",
    medianHourly: 15.5,
    totalEmployment: 3700000,
    growthOutlook: "much faster than average",
    growthPercent: 22,
    educationRequired: "no formal",
    aiExposureScore: 1,
    relatedSkills: [
      "patient care",
      "vital signs",
      "personal hygiene assistance",
      "medication reminders",
      "CPR",
      "first aid",
      "mobility assistance",
      "compassion",
    ],
    vertical: "healthcare",
  },
  {
    title: "Nursing Assistants",
    blsCode: "31-1131",
    medianPay: 36400,
    payType: "annual",
    medianHourly: 17.5,
    totalEmployment: 1400000,
    growthOutlook: "average",
    growthPercent: 4,
    educationRequired: "some college",
    aiExposureScore: 2,
    relatedSkills: [
      "patient care",
      "vital signs",
      "CNA certification",
      "infection control",
      "medical terminology",
      "electronic health records",
      "patient mobility",
    ],
    vertical: "healthcare",
  },
  {
    title: "Registered Nurses",
    blsCode: "29-1141",
    medianPay: 84300,
    payType: "annual",
    medianHourly: 40.5,
    totalEmployment: 3100000,
    growthOutlook: "faster than average",
    growthPercent: 6,
    educationRequired: "bachelor",
    aiExposureScore: 3,
    relatedSkills: [
      "patient assessment",
      "medication administration",
      "IV therapy",
      "care planning",
      "electronic health records",
      "clinical judgment",
      "patient education",
      "wound care",
    ],
    vertical: "healthcare",
  },
  {
    title: "Medical Assistants",
    blsCode: "31-9092",
    medianPay: 38500,
    payType: "annual",
    medianHourly: 18.5,
    totalEmployment: 743000,
    growthOutlook: "much faster than average",
    growthPercent: 14,
    educationRequired: "some college",
    aiExposureScore: 3,
    relatedSkills: [
      "phlebotomy",
      "vital signs",
      "medical terminology",
      "EHR",
      "patient scheduling",
      "insurance verification",
      "clinical procedures",
    ],
    vertical: "healthcare",
  },
  {
    title: "Phlebotomists",
    blsCode: "31-9097",
    medianPay: 39520,
    payType: "annual",
    medianHourly: 19.0,
    totalEmployment: 135000,
    growthOutlook: "faster than average",
    growthPercent: 8,
    educationRequired: "some college",
    aiExposureScore: 1,
    relatedSkills: [
      "venipuncture",
      "blood collection",
      "specimen handling",
      "infection control",
      "patient identification",
      "lab safety",
    ],
    vertical: "healthcare",
  },
  {
    title: "Physical Therapist Assistants",
    blsCode: "31-2021",
    medianPay: 62400,
    payType: "annual",
    medianHourly: 30.0,
    totalEmployment: 98000,
    growthOutlook: "much faster than average",
    growthPercent: 26,
    educationRequired: "associate",
    aiExposureScore: 1,
    relatedSkills: [
      "therapeutic exercise",
      "patient mobility",
      "rehabilitation",
      "manual therapy",
      "treatment documentation",
      "gait training",
    ],
    vertical: "healthcare",
  },
  {
    title: "EMTs and Paramedics",
    blsCode: "29-2040",
    medianPay: 37440,
    payType: "annual",
    medianHourly: 18.0,
    totalEmployment: 265000,
    growthOutlook: "average",
    growthPercent: 5,
    educationRequired: "some college",
    aiExposureScore: 1,
    relatedSkills: [
      "emergency medical care",
      "CPR",
      "trauma assessment",
      "patient transport",
      "airway management",
      "cardiac monitoring",
      "triage",
    ],
    vertical: "healthcare",
  },
  {
    title: "Licensed Practical Nurses",
    blsCode: "29-2061",
    medianPay: 56160,
    payType: "annual",
    medianHourly: 27.0,
    totalEmployment: 670000,
    growthOutlook: "average",
    growthPercent: 5,
    educationRequired: "some college",
    aiExposureScore: 2,
    relatedSkills: [
      "patient care",
      "medication administration",
      "wound care",
      "vital signs",
      "LPN license",
      "IV therapy",
      "patient documentation",
    ],
    vertical: "healthcare",
  },
  {
    title: "Dental Assistants",
    blsCode: "31-9091",
    medianPay: 39520,
    payType: "annual",
    medianHourly: 19.0,
    totalEmployment: 370000,
    growthOutlook: "faster than average",
    growthPercent: 8,
    educationRequired: "some college",
    aiExposureScore: 2,
    relatedSkills: [
      "dental procedures",
      "X-ray",
      "sterilization",
      "patient scheduling",
      "dental software",
      "chairside assisting",
    ],
    vertical: "healthcare",
  },
  {
    title: "Pharmacy Technicians",
    blsCode: "29-2052",
    medianPay: 38500,
    payType: "annual",
    medianHourly: 18.5,
    totalEmployment: 450000,
    growthOutlook: "average",
    growthPercent: 5,
    educationRequired: "high school",
    aiExposureScore: 5,
    relatedSkills: [
      "medication dispensing",
      "pharmacy software",
      "inventory management",
      "prescription processing",
      "customer service",
      "pharmaceutical calculations",
    ],
    vertical: "healthcare",
  },

  // ── Tech (10) ────────────────────────────────────────────────────────
  {
    title: "Software Developers",
    blsCode: "15-1252",
    medianPay: 124800,
    payType: "annual",
    medianHourly: 60.0,
    totalEmployment: 1800000,
    growthOutlook: "much faster than average",
    growthPercent: 25,
    educationRequired: "bachelor",
    aiExposureScore: 7,
    relatedSkills: [
      "JavaScript",
      "Python",
      "software engineering",
      "Git",
      "agile",
      "REST APIs",
      "cloud computing",
      "data structures",
      "algorithms",
    ],
    vertical: "tech",
  },
  {
    title: "Data Scientists",
    blsCode: "15-2051",
    medianPay: 104000,
    payType: "annual",
    medianHourly: 50.0,
    totalEmployment: 192000,
    growthOutlook: "much faster than average",
    growthPercent: 35,
    educationRequired: "bachelor",
    aiExposureScore: 8,
    relatedSkills: [
      "Python",
      "machine learning",
      "statistics",
      "SQL",
      "data visualization",
      "TensorFlow",
      "R",
      "big data",
    ],
    vertical: "tech",
  },
  {
    title: "Information Security Analysts",
    blsCode: "15-1212",
    medianPay: 114400,
    payType: "annual",
    medianHourly: 55.0,
    totalEmployment: 168000,
    growthOutlook: "much faster than average",
    growthPercent: 32,
    educationRequired: "bachelor",
    aiExposureScore: 6,
    relatedSkills: [
      "cybersecurity",
      "network security",
      "penetration testing",
      "SIEM",
      "risk assessment",
      "incident response",
      "firewall management",
      "compliance",
    ],
    vertical: "tech",
  },
  {
    title: "Web Developers",
    blsCode: "15-1254",
    medianPay: 83200,
    payType: "annual",
    medianHourly: 40.0,
    totalEmployment: 210000,
    growthOutlook: "much faster than average",
    growthPercent: 16,
    educationRequired: "associate",
    aiExposureScore: 7,
    relatedSkills: [
      "HTML",
      "CSS",
      "JavaScript",
      "React",
      "Node.js",
      "responsive design",
      "SEO",
      "web accessibility",
    ],
    vertical: "tech",
  },
  {
    title: "Computer Support Specialists",
    blsCode: "15-1232",
    medianPay: 58240,
    payType: "annual",
    medianHourly: 28.0,
    totalEmployment: 880000,
    growthOutlook: "faster than average",
    growthPercent: 6,
    educationRequired: "some college",
    aiExposureScore: 5,
    relatedSkills: [
      "troubleshooting",
      "help desk",
      "Active Directory",
      "networking",
      "Windows",
      "Linux",
      "customer service",
      "ticketing systems",
    ],
    vertical: "tech",
  },
  {
    title: "Database Administrators",
    blsCode: "15-1242",
    medianPay: 99840,
    payType: "annual",
    medianHourly: 48.0,
    totalEmployment: 168000,
    growthOutlook: "faster than average",
    growthPercent: 8,
    educationRequired: "bachelor",
    aiExposureScore: 7,
    relatedSkills: [
      "SQL",
      "database management",
      "Oracle",
      "MySQL",
      "PostgreSQL",
      "performance tuning",
      "backup and recovery",
      "data modeling",
    ],
    vertical: "tech",
  },
  {
    title: "Network Administrators",
    blsCode: "15-1244",
    medianPay: 87360,
    payType: "annual",
    medianHourly: 42.0,
    totalEmployment: 350000,
    growthOutlook: "slower than average",
    growthPercent: 2,
    educationRequired: "bachelor",
    aiExposureScore: 5,
    relatedSkills: [
      "network configuration",
      "Cisco",
      "TCP/IP",
      "VPN",
      "firewall",
      "network monitoring",
      "cloud networking",
      "DNS",
    ],
    vertical: "tech",
  },
  {
    title: "Computer Systems Analysts",
    blsCode: "15-1211",
    medianPay: 101920,
    payType: "annual",
    medianHourly: 49.0,
    totalEmployment: 530000,
    growthOutlook: "faster than average",
    growthPercent: 10,
    educationRequired: "bachelor",
    aiExposureScore: 8,
    relatedSkills: [
      "systems analysis",
      "requirements gathering",
      "business analysis",
      "ERP",
      "project management",
      "process improvement",
      "technical writing",
    ],
    vertical: "tech",
  },
  {
    title: "IT Project Managers",
    blsCode: "15-1299",
    medianPay: 97760,
    payType: "annual",
    medianHourly: 47.0,
    totalEmployment: 480000,
    growthOutlook: "much faster than average",
    growthPercent: 15,
    educationRequired: "bachelor",
    aiExposureScore: 6,
    relatedSkills: [
      "project management",
      "agile",
      "Scrum",
      "budgeting",
      "stakeholder management",
      "Jira",
      "risk management",
      "team leadership",
    ],
    vertical: "tech",
  },
  {
    title: "UX Designers",
    blsCode: "15-1255",
    medianPay: 87360,
    payType: "annual",
    medianHourly: 42.0,
    totalEmployment: 100000,
    growthOutlook: "much faster than average",
    growthPercent: 16,
    educationRequired: "bachelor",
    aiExposureScore: 6,
    relatedSkills: [
      "user research",
      "wireframing",
      "prototyping",
      "Figma",
      "usability testing",
      "interaction design",
      "information architecture",
      "design systems",
    ],
    vertical: "tech",
  },

  // ── Trades (8) ───────────────────────────────────────────────────────
  {
    title: "Electricians",
    blsCode: "47-2111",
    medianPay: 60320,
    payType: "annual",
    medianHourly: 29.0,
    totalEmployment: 740000,
    growthOutlook: "faster than average",
    growthPercent: 6,
    educationRequired: "high school",
    aiExposureScore: 1,
    relatedSkills: [
      "electrical wiring",
      "NEC code",
      "blueprint reading",
      "circuit testing",
      "conduit bending",
      "safety protocols",
      "troubleshooting",
    ],
    vertical: "trades",
  },
  {
    title: "Plumbers",
    blsCode: "47-2152",
    medianPay: 60320,
    payType: "annual",
    medianHourly: 29.0,
    totalEmployment: 490000,
    growthOutlook: "slower than average",
    growthPercent: 2,
    educationRequired: "high school",
    aiExposureScore: 1,
    relatedSkills: [
      "pipe fitting",
      "plumbing code",
      "blueprint reading",
      "soldering",
      "drain cleaning",
      "water heater installation",
      "safety protocols",
    ],
    vertical: "trades",
  },
  {
    title: "HVAC Technicians",
    blsCode: "49-9021",
    medianPay: 52000,
    payType: "annual",
    medianHourly: 25.0,
    totalEmployment: 394000,
    growthOutlook: "faster than average",
    growthPercent: 6,
    educationRequired: "some college",
    aiExposureScore: 1,
    relatedSkills: [
      "HVAC systems",
      "refrigerant handling",
      "EPA 608 certification",
      "electrical diagnostics",
      "ductwork",
      "thermostat installation",
      "preventive maintenance",
    ],
    vertical: "trades",
  },
  {
    title: "Welders",
    blsCode: "51-4121",
    medianPay: 45760,
    payType: "annual",
    medianHourly: 22.0,
    totalEmployment: 430000,
    growthOutlook: "slower than average",
    growthPercent: 2,
    educationRequired: "high school",
    aiExposureScore: 2,
    relatedSkills: [
      "MIG welding",
      "TIG welding",
      "arc welding",
      "blueprint reading",
      "metal fabrication",
      "safety protocols",
      "quality inspection",
    ],
    vertical: "trades",
  },
  {
    title: "Carpenters",
    blsCode: "47-2031",
    medianPay: 52000,
    payType: "annual",
    medianHourly: 25.0,
    totalEmployment: 740000,
    growthOutlook: "slower than average",
    growthPercent: 2,
    educationRequired: "high school",
    aiExposureScore: 1,
    relatedSkills: [
      "framing",
      "blueprint reading",
      "power tools",
      "finish carpentry",
      "measurement",
      "building code",
      "cabinet installation",
    ],
    vertical: "trades",
  },
  {
    title: "Automotive Service Technicians",
    blsCode: "49-3023",
    medianPay: 47840,
    payType: "annual",
    medianHourly: 23.0,
    totalEmployment: 750000,
    growthOutlook: "average",
    growthPercent: 4,
    educationRequired: "some college",
    aiExposureScore: 2,
    relatedSkills: [
      "engine diagnostics",
      "brake systems",
      "ASE certification",
      "OBD-II",
      "electrical systems",
      "transmission repair",
      "preventive maintenance",
    ],
    vertical: "trades",
  },
  {
    title: "Solar Panel Installers",
    blsCode: "47-2231",
    medianPay: 47840,
    payType: "annual",
    medianHourly: 23.0,
    totalEmployment: 16000,
    growthOutlook: "much faster than average",
    growthPercent: 22,
    educationRequired: "high school",
    aiExposureScore: 1,
    relatedSkills: [
      "solar PV installation",
      "electrical wiring",
      "roof mounting",
      "inverter setup",
      "safety harness",
      "NEC code",
      "system testing",
    ],
    vertical: "trades",
  },
  {
    title: "Construction Laborers",
    blsCode: "47-2061",
    medianPay: 39520,
    payType: "annual",
    medianHourly: 19.0,
    totalEmployment: 1500000,
    growthOutlook: "average",
    growthPercent: 4,
    educationRequired: "no formal",
    aiExposureScore: 1,
    relatedSkills: [
      "heavy lifting",
      "concrete work",
      "demolition",
      "site preparation",
      "OSHA safety",
      "equipment operation",
      "general labor",
    ],
    vertical: "trades",
  },

  // ── Admin/Office (6) ─────────────────────────────────────────────────
  {
    title: "Administrative Assistants",
    blsCode: "43-6014",
    medianPay: 41600,
    payType: "annual",
    medianHourly: 20.0,
    totalEmployment: 3500000,
    growthOutlook: "decline",
    growthPercent: -8,
    educationRequired: "high school",
    aiExposureScore: 8,
    relatedSkills: [
      "Microsoft Office",
      "scheduling",
      "data entry",
      "filing",
      "communication",
      "calendar management",
      "document preparation",
    ],
    vertical: "admin",
  },
  {
    title: "Bookkeeping Clerks",
    blsCode: "43-3031",
    medianPay: 45760,
    payType: "annual",
    medianHourly: 22.0,
    totalEmployment: 1500000,
    growthOutlook: "decline",
    growthPercent: -6,
    educationRequired: "some college",
    aiExposureScore: 9,
    relatedSkills: [
      "QuickBooks",
      "accounts payable",
      "accounts receivable",
      "payroll",
      "reconciliation",
      "spreadsheets",
      "financial reporting",
    ],
    vertical: "admin",
  },
  {
    title: "Receptionists",
    blsCode: "43-4171",
    medianPay: 33280,
    payType: "annual",
    medianHourly: 16.0,
    totalEmployment: 1000000,
    growthOutlook: "decline",
    growthPercent: -5,
    educationRequired: "high school",
    aiExposureScore: 7,
    relatedSkills: [
      "customer service",
      "phone systems",
      "scheduling",
      "data entry",
      "front desk management",
      "multi-tasking",
      "communication",
    ],
    vertical: "admin",
  },
  {
    title: "Human Resources Specialists",
    blsCode: "13-1071",
    medianPay: 66560,
    payType: "annual",
    medianHourly: 32.0,
    totalEmployment: 830000,
    growthOutlook: "faster than average",
    growthPercent: 8,
    educationRequired: "bachelor",
    aiExposureScore: 6,
    relatedSkills: [
      "recruiting",
      "onboarding",
      "HRIS",
      "benefits administration",
      "employee relations",
      "compliance",
      "interviewing",
      "performance management",
    ],
    vertical: "admin",
  },
  {
    title: "Office Managers",
    blsCode: "11-3012",
    medianPay: 62400,
    payType: "annual",
    medianHourly: 30.0,
    totalEmployment: 280000,
    growthOutlook: "average",
    growthPercent: 5,
    educationRequired: "bachelor",
    aiExposureScore: 6,
    relatedSkills: [
      "office administration",
      "budgeting",
      "vendor management",
      "team supervision",
      "Microsoft Office",
      "facilities management",
      "scheduling",
    ],
    vertical: "admin",
  },
  {
    title: "Data Entry Keyers",
    blsCode: "43-9021",
    medianPay: 35360,
    payType: "annual",
    medianHourly: 17.0,
    totalEmployment: 155000,
    growthOutlook: "decline",
    growthPercent: -30,
    educationRequired: "high school",
    aiExposureScore: 10,
    relatedSkills: [
      "typing",
      "data entry",
      "spreadsheets",
      "attention to detail",
      "database software",
      "10-key",
      "data verification",
    ],
    vertical: "admin",
  },

  // ── Food Service (6) ─────────────────────────────────────────────────
  {
    title: "Cooks",
    blsCode: "35-2014",
    medianPay: 31200,
    payType: "annual",
    medianHourly: 15.0,
    totalEmployment: 1500000,
    growthOutlook: "average",
    growthPercent: 5,
    educationRequired: "no formal",
    aiExposureScore: 2,
    relatedSkills: [
      "food preparation",
      "knife skills",
      "food safety",
      "menu planning",
      "grill operation",
      "inventory management",
      "time management",
    ],
    vertical: "food_service",
  },
  {
    title: "Food Service Managers",
    blsCode: "11-9051",
    medianPay: 60320,
    payType: "annual",
    medianHourly: 29.0,
    totalEmployment: 450000,
    growthOutlook: "faster than average",
    growthPercent: 10,
    educationRequired: "high school",
    aiExposureScore: 4,
    relatedSkills: [
      "restaurant management",
      "staff scheduling",
      "food safety",
      "budgeting",
      "customer service",
      "inventory control",
      "POS systems",
      "team leadership",
    ],
    vertical: "food_service",
  },
  {
    title: "Waiters and Waitresses",
    blsCode: "35-3031",
    medianPay: 29120,
    payType: "annual",
    medianHourly: 14.0,
    totalEmployment: 2500000,
    growthOutlook: "faster than average",
    growthPercent: 6,
    educationRequired: "no formal",
    aiExposureScore: 2,
    relatedSkills: [
      "customer service",
      "POS systems",
      "food knowledge",
      "multi-tasking",
      "communication",
      "upselling",
      "teamwork",
    ],
    vertical: "food_service",
  },
  {
    title: "Bartenders",
    blsCode: "35-3011",
    medianPay: 29120,
    payType: "annual",
    medianHourly: 14.0,
    totalEmployment: 680000,
    growthOutlook: "faster than average",
    growthPercent: 7,
    educationRequired: "no formal",
    aiExposureScore: 1,
    relatedSkills: [
      "mixology",
      "customer service",
      "POS systems",
      "inventory management",
      "responsible alcohol service",
      "cash handling",
      "communication",
    ],
    vertical: "food_service",
  },
  {
    title: "Food Preparation Workers",
    blsCode: "35-2021",
    medianPay: 29120,
    payType: "annual",
    medianHourly: 14.0,
    totalEmployment: 900000,
    growthOutlook: "slower than average",
    growthPercent: 2,
    educationRequired: "no formal",
    aiExposureScore: 2,
    relatedSkills: [
      "food preparation",
      "knife skills",
      "food safety",
      "sanitation",
      "portion control",
      "kitchen equipment",
      "teamwork",
    ],
    vertical: "food_service",
  },
  {
    title: "Bakers",
    blsCode: "51-3011",
    medianPay: 31200,
    payType: "annual",
    medianHourly: 15.0,
    totalEmployment: 200000,
    growthOutlook: "faster than average",
    growthPercent: 8,
    educationRequired: "no formal",
    aiExposureScore: 1,
    relatedSkills: [
      "baking techniques",
      "food safety",
      "recipe scaling",
      "decorating",
      "inventory management",
      "oven operation",
      "quality control",
    ],
    vertical: "food_service",
  },

  // ── Transport (6) ────────────────────────────────────────────────────
  {
    title: "Delivery and Truck Drivers",
    blsCode: "53-3032",
    medianPay: 49920,
    payType: "annual",
    medianHourly: 24.0,
    totalEmployment: 2000000,
    growthOutlook: "average",
    growthPercent: 4,
    educationRequired: "high school",
    aiExposureScore: 3,
    relatedSkills: [
      "CDL",
      "route planning",
      "vehicle inspection",
      "DOT regulations",
      "defensive driving",
      "load securing",
      "GPS navigation",
    ],
    vertical: "transport",
  },
  {
    title: "Warehouse Workers",
    blsCode: "53-7065",
    medianPay: 33280,
    payType: "annual",
    medianHourly: 16.0,
    totalEmployment: 1800000,
    growthOutlook: "decline",
    growthPercent: -2,
    educationRequired: "no formal",
    aiExposureScore: 4,
    relatedSkills: [
      "forklift operation",
      "inventory management",
      "order picking",
      "packing",
      "WMS",
      "shipping and receiving",
      "safety protocols",
    ],
    vertical: "transport",
  },
  {
    title: "Bus Drivers",
    blsCode: "53-3052",
    medianPay: 45760,
    payType: "annual",
    medianHourly: 22.0,
    totalEmployment: 700000,
    growthOutlook: "faster than average",
    growthPercent: 6,
    educationRequired: "high school",
    aiExposureScore: 3,
    relatedSkills: [
      "CDL",
      "passenger safety",
      "route navigation",
      "vehicle inspection",
      "defensive driving",
      "customer service",
      "ADA compliance",
    ],
    vertical: "transport",
  },
  {
    title: "Taxi and Rideshare Drivers",
    blsCode: "53-3054",
    medianPay: 31200,
    payType: "annual",
    medianHourly: 15.0,
    totalEmployment: 350000,
    growthOutlook: "decline",
    growthPercent: -9,
    educationRequired: "no formal",
    aiExposureScore: 5,
    relatedSkills: [
      "navigation",
      "customer service",
      "vehicle maintenance",
      "defensive driving",
      "ride-hailing apps",
      "local area knowledge",
    ],
    vertical: "transport",
  },
  {
    title: "Logistics Coordinators",
    blsCode: "13-1081",
    medianPay: 49920,
    payType: "annual",
    medianHourly: 24.0,
    totalEmployment: 900000,
    growthOutlook: "much faster than average",
    growthPercent: 18,
    educationRequired: "bachelor",
    aiExposureScore: 6,
    relatedSkills: [
      "supply chain management",
      "ERP systems",
      "inventory tracking",
      "vendor management",
      "data analysis",
      "Excel",
      "freight coordination",
    ],
    vertical: "transport",
  },
  {
    title: "Postal Service Workers",
    blsCode: "43-5052",
    medianPay: 54080,
    payType: "annual",
    medianHourly: 26.0,
    totalEmployment: 340000,
    growthOutlook: "decline",
    growthPercent: -10,
    educationRequired: "high school",
    aiExposureScore: 3,
    relatedSkills: [
      "mail sorting",
      "route management",
      "customer service",
      "vehicle operation",
      "physical stamina",
      "postal regulations",
    ],
    vertical: "transport",
  },

  // ── Retail (4) ───────────────────────────────────────────────────────
  {
    title: "Retail Salespersons",
    blsCode: "41-2031",
    medianPay: 31200,
    payType: "annual",
    medianHourly: 15.0,
    totalEmployment: 4300000,
    growthOutlook: "decline",
    growthPercent: -2,
    educationRequired: "no formal",
    aiExposureScore: 4,
    relatedSkills: [
      "customer service",
      "sales techniques",
      "product knowledge",
      "POS systems",
      "cash handling",
      "visual merchandising",
      "communication",
    ],
    vertical: "retail",
  },
  {
    title: "Cashiers",
    blsCode: "41-2011",
    medianPay: 29120,
    payType: "annual",
    medianHourly: 14.0,
    totalEmployment: 3300000,
    growthOutlook: "decline",
    growthPercent: -10,
    educationRequired: "no formal",
    aiExposureScore: 7,
    relatedSkills: [
      "cash handling",
      "POS systems",
      "customer service",
      "basic math",
      "bagging",
      "returns processing",
      "communication",
    ],
    vertical: "retail",
  },
  {
    title: "Store Managers",
    blsCode: "11-1021",
    medianPay: 49920,
    payType: "annual",
    medianHourly: 24.0,
    totalEmployment: 380000,
    growthOutlook: "average",
    growthPercent: 3,
    educationRequired: "high school",
    aiExposureScore: 4,
    relatedSkills: [
      "team management",
      "inventory control",
      "sales analysis",
      "customer service",
      "budgeting",
      "loss prevention",
      "scheduling",
      "hiring",
    ],
    vertical: "retail",
  },
  {
    title: "Stock Clerks",
    blsCode: "43-5081",
    medianPay: 31200,
    payType: "annual",
    medianHourly: 15.0,
    totalEmployment: 1800000,
    growthOutlook: "decline",
    growthPercent: -4,
    educationRequired: "no formal",
    aiExposureScore: 5,
    relatedSkills: [
      "inventory management",
      "receiving",
      "stocking",
      "organization",
      "physical stamina",
      "scanner operation",
      "attention to detail",
    ],
    vertical: "retail",
  },
];

// ── Helper utilities ─────────────────────────────────────────────────────────

/** Return all distinct vertical names */
export function getVerticals(): string[] {
  return Array.from(new Set(BLS_OCCUPATIONS.map((o) => o.vertical)));
}

/** Lookup a single occupation by SOC code */
export function getOccupationByCode(
  blsCode: string,
): BLSOccupation | undefined {
  return BLS_OCCUPATIONS.find((o) => o.blsCode === blsCode);
}

/** Find occupations whose relatedSkills overlap with the provided list */
export function matchOccupationsBySkills(
  skills: string[],
  minMatchCount = 1,
): BLSOccupation[] {
  const lower = skills.map((s) => s.toLowerCase());
  return BLS_OCCUPATIONS.filter((o) => {
    const matched = o.relatedSkills.filter((rs) =>
      lower.some((s) => rs.toLowerCase().includes(s) || s.includes(rs.toLowerCase())),
    );
    return matched.length >= minMatchCount;
  });
}

/** Compute the skill gap between a user's skills and a target occupation */
export function computeSkillGap(
  currentSkills: string[],
  target: BLSOccupation,
): string[] {
  const lower = currentSkills.map((s) => s.toLowerCase());
  return target.relatedSkills.filter(
    (rs) => !lower.some((s) => rs.toLowerCase().includes(s) || s.includes(rs.toLowerCase())),
  );
}

/** Estimate learning time based on education gap and skill gap count */
export function estimateLearningTime(
  skillGapCount: number,
  currentEducation: string,
  targetEducation: string,
): string {
  const eduLevels = [
    "no formal",
    "high school",
    "some college",
    "associate",
    "bachelor",
    "master",
    "doctoral",
  ];

  const currentIdx = eduLevels.indexOf(currentEducation);
  const targetIdx = eduLevels.indexOf(targetEducation);
  const eduGap = Math.max(0, targetIdx - currentIdx);

  // Base months from education gap
  const eduMonths = eduGap * 12;
  // Additional months for skill acquisition (roughly 1-2 months per skill)
  const skillMonths = skillGapCount * 1.5;

  const totalMonths = Math.ceil(eduMonths + skillMonths);

  if (totalMonths <= 3) return "1-3 months";
  if (totalMonths <= 6) return "3-6 months";
  if (totalMonths <= 12) return "6-12 months";
  if (totalMonths <= 24) return "1-2 years";
  if (totalMonths <= 48) return "2-4 years";
  return "4+ years";
}
