/**
 * Pre-cached training catalog per skill — Phase 5.
 *
 * Today `/api/upskill/find` calls Claude on every page load. Slow
 * (3-5 sec) and ~$0.02 per call. With 100 daily users browsing 5
 * skill cards each, that's $50/mo just for upskill lookups.
 *
 * This script pre-fills top 3 free + top 3 paid training options per
 * skill into lib/training-catalog.ts. Page loads are instant after
 * this ships. In-person training stays runtime (requires zip).
 *
 * Cost: ~$25 one-time (Haiku 4.5, ~210 batches of 10 skills).
 * Output: lib/training-catalog.ts.
 *
 * Run: cd ~/workpath && npx tsx scripts/generate-training-catalog.ts
 */

import * as fs from "node:fs";
import * as path from "node:path";
import * as dotenv from "dotenv";
dotenv.config({ path: path.resolve(__dirname, "../.env") });
import Anthropic from "@anthropic-ai/sdk";
import { TAXONOMY } from "../lib/taxonomy";

const OUTPUT = path.resolve(__dirname, "../lib/training-catalog.ts");
const BATCH_SIZE = 10;
const MODEL = "claude-haiku-4-5-20251001";

const client = new Anthropic();

const PROMPT_PREFIX = `For each skill, list the top 3 FREE online training options + top 3 PAID online training options that an entry-level US worker could realistically use to learn it.

RULES:
- Real, currently-available resources. Don't invent.
- Prefer mainstream platforms: Coursera, Udemy, edX, Khan Academy, YouTube, LinkedIn Learning, Red Cross, OSHA Outreach, official certification bodies.
- For physical / certification skills (CPR, OSHA-10, HHA Certification), name the legitimate cert body or in-person trainers' typical platforms.
- Skip the skill entirely if no credible training exists (return an empty object — don't make things up).

Return ONLY a JSON object of this shape:
{
  "Customer Service": {
    "free": [
      {"title": "Customer Service Fundamentals (Free Course)", "provider": "HubSpot Academy", "url": "https://academy.hubspot.com/courses/inbound-service", "duration": "5 hrs"},
      ...
    ],
    "paid": [
      {"title": "Customer Service Mastery", "provider": "Udemy", "url": "https://www.udemy.com/topic/customer-service/", "duration": "12 hrs", "priceUSD": 30},
      ...
    ]
  }
}

DO NOT include prose. JSON only.

Skills:
`;

async function runBatch(skills: string[]): Promise<Record<string, unknown>> {
  const userMsg =
    PROMPT_PREFIX +
    skills.map((s, i) => `${i + 1}. ${s}`).join("\n") +
    "\n\nReturn JSON:";

  // Prefill the assistant's response with `{` so it has no choice but
  // to continue as JSON. Critical for batch reliability — without this
  // Haiku 4.5 returns prose ~90% of the time at this output size.
  const res = await client.messages.create({
    model: MODEL,
    max_tokens: 4000,
    messages: [
      { role: "user", content: userMsg },
      { role: "assistant", content: "{" },
    ],
  });

  let text = (res.content[0] as { type: string; text: string }).text.trim();
  // Re-attach the prefilled opening brace.
  if (!text.startsWith("{")) text = "{" + text;
  // Strip any trailing code fence or extra text.
  text = text.replace(/```\s*$/, "").trim();
  // Truncate at last balanced closing brace if the response was cut off.
  const lastBrace = text.lastIndexOf("}");
  if (lastBrace > 0 && lastBrace < text.length - 1) text = text.slice(0, lastBrace + 1);

  try {
    return JSON.parse(text);
  } catch {
    return {};
  }
}

async function main() {
  const allSkills = new Set<string>();
  for (const entry of TAXONOMY) {
    for (const s of entry.skills) allSkills.add(s);
  }
  const skills = Array.from(allSkills).sort();
  console.log(`${skills.length} distinct skills → ~${Math.ceil(skills.length / BATCH_SIZE)} batches`);

  // Resume from any prior partial run if the catalog file exists.
  // Lets us pick up after a crash without re-spending API credits.
  let catalog: Record<string, unknown> = {};
  if (fs.existsSync(OUTPUT)) {
    try {
      const prior = fs.readFileSync(OUTPUT, "utf8");
      const m = prior.match(/TRAINING_CATALOG: Record<string, TrainingCatalogEntry> = ([\s\S]+?);\s*\n/);
      if (m) {
        catalog = JSON.parse(m[1]);
        console.log(`  resuming with ${Object.keys(catalog).length} cached entries`);
      }
    } catch {
      // Couldn't parse — start fresh
    }
  }

  // Write the (possibly partial) catalog to disk. Called every batch.
  const flush = () => {
    const lines: string[] = [];
    lines.push(`/** Pre-cached training catalog — Phase 5. Generated by scripts/generate-training-catalog.ts. */`);
    lines.push("");
    lines.push(`export interface TrainingResource {`);
    lines.push(`  title: string; provider: string; url: string; duration?: string; priceUSD?: number;`);
    lines.push(`}`);
    lines.push(`export interface TrainingCatalogEntry { free: TrainingResource[]; paid: TrainingResource[]; }`);
    lines.push("");
    lines.push(`export const TRAINING_CATALOG: Record<string, TrainingCatalogEntry> = ${JSON.stringify(catalog, null, 2)};`);
    lines.push("");
    lines.push(`export function getTrainingFor(skill: string): TrainingCatalogEntry | null {`);
    lines.push(`  return (TRAINING_CATALOG as Record<string, TrainingCatalogEntry>)[skill] ?? null;`);
    lines.push(`}`);
    lines.push("");
    fs.writeFileSync(OUTPUT, lines.join("\n"));
  };

  for (let i = 0; i < skills.length; i += BATCH_SIZE) {
    const batch = skills.slice(i, i + BATCH_SIZE);
    // Skip batches where every skill is already in the catalog.
    const remaining = batch.filter((s) => !catalog[s]);
    if (remaining.length === 0) continue;

    process.stdout.write(`  batch ${Math.floor(i / BATCH_SIZE) + 1}/${Math.ceil(skills.length / BATCH_SIZE)}…`);
    try {
      const result = await runBatch(remaining);
      let added = 0;
      for (const [k, v] of Object.entries(result)) {
        catalog[k] = v;
        added++;
      }
      flush(); // Save after every successful batch
      process.stdout.write(` ${added} cached (${Object.keys(catalog).length}/${skills.length})\n`);
    } catch (e) {
      process.stdout.write(` failed: ${e instanceof Error ? e.message : "unknown"}\n`);
    }
  }

  console.log(`\nGenerated ${Object.keys(catalog).length} training entries`);
  flush();
  console.log(`Wrote ${OUTPUT}`);
}

main().catch((e) => {
  console.error("fatal:", e);
  process.exit(1);
});
