/**
 * Equivalency generation — Phase 2 of Caroline's taxonomy ladder.
 *
 * "Customer Service ≈ Client Relations ≈ Guest Relations ≈ Customer Support"
 * was Caroline's exact example. Today these match nobody to each other —
 * a recruiter searching "Client Relations" silently misses candidates
 * who wrote "Customer Service". This script generates the equivalency
 * map via Claude, then emits lib/equivalencies.ts which the cluster
 * classifier uses to canonicalize before scoring.
 *
 * Run: cd ~/workpath && npx tsx scripts/generate-equivalencies.ts
 *
 * Cost: ~$2 in Claude calls (Sonnet 4, ~85 batches of 25 skills each).
 *
 * Output: lib/equivalencies.ts exporting:
 *   - EQUIVALENCIES: Record<canonical, synonyms[]>
 *   - canonicalize(skill: string): string  — folds synonyms to canonical
 */

import * as fs from "node:fs";
import * as path from "node:path";
import * as dotenv from "dotenv";
dotenv.config({ path: path.resolve(__dirname, "../.env") });
import Anthropic from "@anthropic-ai/sdk";
import { TAXONOMY } from "../lib/taxonomy";

const OUTPUT = path.resolve(__dirname, "../lib/equivalencies.ts");
const BATCH_SIZE = 25;
const MODEL = "claude-haiku-4-5-20251001";

const client = new Anthropic();

const PROMPT_PREFIX = `For each skill, list 1-3 common synonym phrases that recruiters or workers might use interchangeably to mean the SAME competency.

RULES:
- Synonyms must be specific equivalents, not parent concepts or related skills.
- Skip skills that have no common synonyms (just return an empty array).
- Prefer phrases that real job listings or worker profiles use.

EXAMPLES:
{
  "Customer Service": ["Client Relations", "Guest Relations", "Customer Support"],
  "Wound Care": ["Dressing Changes", "Bandaging"],
  "Inventory Management": ["Stock Control", "Stockroom Management"],
  "Reading Comprehension": [],
  "Critical Thinking": []
}

DO NOT INCLUDE:
- Parent concepts (e.g. "Customer Service" ≠ "Communication")
- Related but distinct skills (e.g. "Wound Care" ≠ "First Aid")
- Made-up jargon

Return ONLY a JSON object mapping each input skill to its synonym array. No prose.

Skills to expand:
`;

async function runBatch(skills: string[]): Promise<Record<string, string[]>> {
  const userMsg =
    PROMPT_PREFIX +
    skills.map((s, i) => `${i + 1}. ${s}`).join("\n") +
    "\n\nReturn JSON:";

  const res = await client.messages.create({
    model: MODEL,
    max_tokens: 2048,
    messages: [{ role: "user", content: userMsg }],
  });

  const text = (res.content[0] as { type: string; text: string }).text
    .replace(/^```(?:json)?\s*/i, "")
    .replace(/```\s*$/, "")
    .trim();

  try {
    return JSON.parse(text);
  } catch (e) {
    console.warn("  parse error on batch — skipping:", e);
    return {};
  }
}

async function main() {
  // Collect every distinct skill across the entire taxonomy.
  const allSkills = new Set<string>();
  for (const entry of TAXONOMY) {
    for (const s of entry.skills) allSkills.add(s);
  }
  const skills = Array.from(allSkills).sort();
  console.log(`${skills.length} distinct skills → ~${Math.ceil(skills.length / BATCH_SIZE)} batches`);

  const equivalencies: Record<string, string[]> = {};
  let processed = 0;

  for (let i = 0; i < skills.length; i += BATCH_SIZE) {
    const batch = skills.slice(i, i + BATCH_SIZE);
    process.stdout.write(`  batch ${Math.floor(i / BATCH_SIZE) + 1}/${Math.ceil(skills.length / BATCH_SIZE)}…`);
    try {
      const result = await runBatch(batch);
      let added = 0;
      for (const [k, v] of Object.entries(result)) {
        if (Array.isArray(v) && v.length > 0) {
          equivalencies[k] = v;
          added++;
        }
      }
      processed += batch.length;
      process.stdout.write(` ${added} mapped (${processed}/${skills.length})\n`);
    } catch (e) {
      console.warn(` failed: ${e instanceof Error ? e.message : "unknown"}`);
    }
  }

  console.log(`\nGenerated ${Object.keys(equivalencies).length} canonical→synonym mappings`);

  // Emit lib/equivalencies.ts
  const lines: string[] = [];
  lines.push(`/**`);
  lines.push(` * Skill equivalencies — Phase 2 of Caroline's taxonomy ladder.`);
  lines.push(` *`);
  lines.push(` * Generated by scripts/generate-equivalencies.ts from the O*NET-derived`);
  lines.push(` * taxonomy. Maps each canonical skill name (the key) to recruiter/`);
  lines.push(` * worker-facing synonyms (the array).`);
  lines.push(` *`);
  lines.push(` * Used by classifySkillCluster() in lib/taxonomy.ts: before scoring`);
  lines.push(` * a basket, every skill is canonicalized through SYNONYM_INDEX so that`);
  lines.push(` * "Client Relations" matches the same node as "Customer Service".`);
  lines.push(` */`);
  lines.push("");
  lines.push(`export const EQUIVALENCIES: Record<string, string[]> = ${JSON.stringify(equivalencies, null, 2)};`);
  lines.push("");
  lines.push(`// Reverse index: synonym (lowercased) → canonical name.`);
  lines.push(`const SYNONYM_INDEX: Map<string, string> = (() => {`);
  lines.push(`  const m = new Map<string, string>();`);
  lines.push(`  for (const [canonical, synonyms] of Object.entries(EQUIVALENCIES)) {`);
  lines.push(`    for (const syn of synonyms) m.set(syn.toLowerCase(), canonical);`);
  lines.push(`  }`);
  lines.push(`  return m;`);
  lines.push(`})();`);
  lines.push("");
  lines.push(`/**`);
  lines.push(` * Fold a user-typed skill to its canonical form, if a synonym is known.`);
  lines.push(` * "Client Relations" → "Customer Service". Falls back to the input.`);
  lines.push(` */`);
  lines.push(`export function canonicalize(skill: string): string {`);
  lines.push(`  return SYNONYM_INDEX.get(skill.toLowerCase()) ?? skill;`);
  lines.push(`}`);
  lines.push("");

  fs.writeFileSync(OUTPUT, lines.join("\n"));
  console.log(`Wrote ${OUTPUT}`);
}

main().catch((e) => {
  console.error("fatal:", e);
  process.exit(1);
});
